<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Video extends \App\Entity\Video implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_module', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'no', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'pieces', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_etablissement', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_formation', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_promotion', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_semestre', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_modulee', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_element', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'slug'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_module', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'no', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'pieces', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_etablissement', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_formation', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_promotion', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_semestre', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_modulee', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'id_element', '' . "\0" . 'App\\Entity\\Video' . "\0" . 'slug'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Video $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdModule(): ?\App\Entity\AcModule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdModule', []);

        return parent::getIdModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdModule(?\App\Entity\AcModule $id_module): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdModule', [$id_module]);

        return parent::setIdModule($id_module);
    }

    /**
     * {@inheritDoc}
     */
    public function getNo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNo', []);

        return parent::getNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNo(?string $no): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNo', [$no]);

        return parent::setNo($no);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(?string $video): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?string $image): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPieces(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPieces', []);

        return parent::getPieces();
    }

    /**
     * {@inheritDoc}
     */
    public function addPiece(\App\Entity\Pieces $piece): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPiece', [$piece]);

        return parent::addPiece($piece);
    }

    /**
     * {@inheritDoc}
     */
    public function removePiece(\App\Entity\Pieces $piece): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePiece', [$piece]);

        return parent::removePiece($piece);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiece(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiece', []);

        return parent::getPiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiece(?string $piece): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiece', [$piece]);

        return parent::setPiece($piece);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEtablissement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEtablissement', []);

        return parent::getIdEtablissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEtablissement(?int $id_etablissement): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEtablissement', [$id_etablissement]);

        return parent::setIdEtablissement($id_etablissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFormation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFormation', []);

        return parent::getIdFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFormation(?int $id_formation): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFormation', [$id_formation]);

        return parent::setIdFormation($id_formation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPromotion(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPromotion', []);

        return parent::getIdPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPromotion(?int $id_promotion): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPromotion', [$id_promotion]);

        return parent::setIdPromotion($id_promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSemestre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSemestre', []);

        return parent::getIdSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSemestre(?int $id_semestre): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSemestre', [$id_semestre]);

        return parent::setIdSemestre($id_semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdModulee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdModulee', []);

        return parent::getIdModulee();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdModulee(?int $id_modulee): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdModulee', [$id_modulee]);

        return parent::setIdModulee($id_modulee);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdElement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdElement', []);

        return parent::getIdElement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdElement(?int $id_element): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdElement', [$id_element]);

        return parent::setIdElement($id_element);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(?string $slug): \App\Entity\Video
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

}
