<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::api'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api']], [], []],
    'video' => [['slug'], ['_controller' => 'App\\Controller\\DefaultController::video'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/video']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\DefaultController::home'], [], [['text', '/']], [], []],
    'insertVideo' => [[], ['_controller' => 'App\\Controller\\DefaultController::insertVideo'], [], [['text', '/insertVideo']], [], []],
    'info_piece' => [[], ['_controller' => 'App\\Controller\\DefaultController::infoPiece'], [], [['text', '/info_piece']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\DefaultController::login'], [], [['text', '/login']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
