<?php

namespace Container9EOZQoS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WjaVfkeService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.WjaVfke' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WjaVfke'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'acModuleRepository' => ['privates', 'App\\Repository\\AcModuleRepository', 'getAcModuleRepositoryService', true],
        ], [
            'acModuleRepository' => 'App\\Repository\\AcModuleRepository',
        ]);
    }
}
