name: AWS
on: [push]
env:
  TAG: 0.0.1
  DEPLOYMENT: ${{ github.event.repository.name }}
  AWS_CLUSTER: fcz-dev-eks
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MITS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MITS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MITS_AWS_REGION }}

      - name: (ECR) Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: (ECR) Push
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.DEPLOYMENT }}:${{ env.TAG }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.DEPLOYMENT }}:${{ env.TAG }}         
  Deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MITS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MITS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MITS_AWS_REGION }}

      - name: (ECR) Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: (EKS) Deploy
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.MITS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.MITS_AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.MITS_AWS_REGION }}
          cluster_name: ${{ env.AWS_CLUSTER }}
        with:
          args: |
            cd cicd/ ; chmod +x aws.sh ; ./aws.sh ${{ env.DEPLOYMENT }} ${{ env.TAG }} | kubectl apply -f -
            #kubectl rollout status deploy ${{ env.DEPLOYMENT }}
